/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LookupManagementRouteImport } from './routes/lookup-management'
import { Route as TenantsIndexRouteImport } from './routes/tenants.index'
import { Route as TenantsTenantIdRouteImport } from './routes/tenants.$tenantId'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as UsersDetailRouteImport } from './routes/users/detail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupManagementRoute = LookupManagementRouteImport.update({
  id: '/lookup-management',
  path: '/lookup-management',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsTenantIdRoute = TenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersDetailRoute = UsersDetailRouteImport.update({
  id: '/users/detail',
  path: '/users/detail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/lookup-management': typeof LookupManagementRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/detail': typeof UsersDetailRoute
  '/tenants/': typeof TenantsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/lookup-management': typeof LookupManagementRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/detail': typeof UsersDetailRoute
  '/tenants': typeof TenantsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/lookup-management': typeof LookupManagementRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/detail': typeof UsersDetailRoute
  '/tenants/': typeof TenantsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/lookup-management'
    | '/tenants/$tenantId'
    | '/users/$userId'
    | '/users/detail'
    | '/tenants/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/lookup-management'
    | '/tenants/$tenantId'
    | '/users/$userId'
    | '/users/detail'
    | '/tenants'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/lookup-management'
    | '/tenants/$tenantId'
    | '/users/$userId'
    | '/users/detail'
    | '/tenants/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LookupManagementRoute: typeof LookupManagementRoute
  TenantsTenantIdRoute: typeof TenantsTenantIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersDetailRoute: typeof UsersDetailRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup-management': {
      id: '/lookup-management'
      path: '/lookup-management'
      fullPath: '/lookup-management'
      preLoaderRoute: typeof LookupManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$tenantId': {
      id: '/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof TenantsTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/detail': {
      id: '/users/detail'
      path: '/users/detail'
      fullPath: '/users/detail'
      preLoaderRoute: typeof UsersDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LookupManagementRoute: LookupManagementRoute,
  TenantsTenantIdRoute: TenantsTenantIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  UsersDetailRoute: UsersDetailRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
